name 'nfs_server'
maintainer 'Morgan Lieberthal'
maintainer_email 'j.morgan.lieberthal@gmail.com'
license 'mit'
description 'Installs/Configures nfs_server'
long_description 'Installs/Configures nfs_server'
version '0.3.0'

depends 'nfs', '~> 2.2'
depends 'firewalld', '~> 1.1'
